ifeq ($(BLE),1)

export BLE_USE_TWS_SYNC ?= 1
ifeq ($(BLE_USE_TWS_SYNC),1)
KBUILD_CPPFLAGS += -DBLE_USE_TWS_SYNC
endif #BLE_USE_TWS_SYNC

ifeq ($(BLE_AUDIO_ENABLED),1)

##################BLE BIS CONFIG###########################

export APP_BLE_BIS_DELEG_ENABLE ?= 1
export APP_BLE_BIS_SINK_ENABLE ?= 1
ifeq ($(AOB_MOBILE_ENABLED),1)
export APP_BLE_BIS_SRC_ENABLE ?= 1
export APP_BLE_BIS_ASSIST_ENABLE ?= 1
else
export APP_BLE_BIS_SRC_ENABLE ?= 0
export APP_BLE_BIS_ASSIST_ENABLE ?= 0
endif

export CFG_BAP_BC := 0
ifeq ($(APP_BLE_BIS_SRC_ENABLE),1)
KBUILD_CPPFLAGS += -DAPP_BLE_BIS_SRC_ENABLE
CFG_BAP_BC := 1
endif #APP_BLE_BIS_SRC_ENABLE

ifeq ($(APP_BLE_BIS_ASSIST_ENABLE),1)
KBUILD_CPPFLAGS += -DAPP_BLE_BIS_ASSIST_ENABLE
CFG_BAP_BC := 1
endif #APP_BLE_BIS_ASSIST_ENABLE

ifeq ($(APP_BLE_BIS_DELEG_ENABLE),1)
KBUILD_CPPFLAGS += -DAPP_BLE_BIS_DELEG_ENABLE
CFG_BAP_BC := 1
endif #APP_BLE_BIS_DELEG_ENABLE

ifeq ($(APP_BLE_BIS_SINK_ENABLE),1)
KBUILD_CPPFLAGS += -DAPP_BLE_BIS_SINK_ENABLE
CFG_BAP_BC := 1
endif #APP_BLE_BIS_SINK_ENABLE

ifeq ($(CFG_BAP_BC),1)
KBUILD_CPPFLAGS += -DCFG_BAP_BC
endif
####################BLE BIS CONFIG END####################

export BLE_PERIPHERAL_ONLY ?= 0
ifeq ($(BLE_PERIPHERAL_ONLY),1)
KBUILD_CPPFLAGS += -DBLE_PERIPHERAL_ONLY
endif

export BLE_GATT_CLIENT_DISABLE ?= 0
ifeq ($(BLE_GATT_CLIENT_DISABLE),1)
KBUILD_CPPFLAGS += -DBLE_GATT_CLIENT_DISABLE
endif

export BLE_PERIODIC_ADV_DISABLE ?= 0
ifeq ($(BLE_PERIODIC_ADV_DISABLE),1)
KBUILD_CPPFLAGS += -DBLE_PERIODIC_ADV_DISABLE
endif

export BT_LOG_SIMPLIFY ?= 0
ifeq ($(BT_LOG_SIMPLIFY),1)
KBUILD_CPPFLAGS += -DBT_LOG_SIMPLIFY
endif

endif #BLE_AUDIO_ENABLED

endif #BLE
