#cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))

ccflags-y += \
    $(BLUETOOTH_ADAPTER_INCLUDES) \
    -Iutils/cqueue \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libAACdec/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libAACenc/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libFDK/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libMpegTPDec/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libMpegTPEnc/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libPCMutils/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libSBRdec/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libSBRenc/include \
    -Imultimedia/inc/audio/codec/fdkaac_codec/libSYS/include
